In [ ]:
a=10
a

10

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
a=20
b=30
print(a)
b

20


30

In [ ]:
a=[1,2,3,4,5,6,7,8,9]
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.argmax(a))

4


In [ ]:
print(np.min(a))

1


In [ ]:
print(np.where(a>3))

(array([3, 4]),)


In [ ]:
r=np.random.randint(1,20,20)
print(r)

[12  3  5  4  2 16 14 19  7  1 16 17  3 15 19 15  1  2 12 14]


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a,b)

[1 2 3 4 5] [ 6  7  8  9 10]


In [ ]:
a=np.array([1,2,3,4,5])
np.save("ps.npy",a)
print(np.corrcoef(a,b))

[[1. 1.]
 [1. 1.]]


In [ ]:
a=np.array([1,2,3,4,5])
print(a[2:4])

[3 4]


In [ ]:
print(a[:2])

[1 2]


In [ ]:
print(a[2:])

[3 4 5]


In [ ]:
print(a[3:])

[4 5]


In [ ]:
print(a[-3:])

[3 4 5]


In [ ]:
print(a[:-3])

[1 2]


In [ ]:
Arr=np.array([[1,2,3,4,],[3,4,5,6],[7,8,9,2]])
print(Arr[0:1,1:3])

[[2 3]]


In [ ]:
print(Arr[:,1:2])

[[2]
 [4]
 [8]]


In [ ]:
print(Arr[:,::2])

[[1 3]
 [3 5]
 [7 9]]


In [ ]:
import pandas  as pd

In [ ]:
d={
    "Name":["kavi","gowtham","kavin"],
    "Age":["20,21,5"]
}

In [ ]:
print(d["Age"],d["Name"])

['20,21,5'] ['kavi', 'gowtham', 'kavin']
